version: '3.7'
services:
  web:
    build: ./web
#    image: mikeryan56/sufee-admin-flask:1.2.0
    image: mikeryan56/sufee-admin-flask:latest
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    environment:
      VIRTUAL_HOST: sufee-admin.devsetgo.com
      LETSENCRYPT_HOST: sufee-admin.devsetgo.com
#   deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#      restart_policy:
#        condition: always